name: Build LIFE+ APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: stable
          cache: true

      - name: Buat struktur Flutter Android
        run: |
          mkdir /tmp/life_template
          cd /tmp
          flutter create -t app life_template

      - name: Salin kode LIFE+
        run: |
          cp -r lib /tmp/life_template/
          cp pubspec.yaml /tmp/life_template/

      - name: Build project
        working-directory: /tmp/life_template
        run: |
          flutter pub get
          flutter build apk --release

      - name: Simpan APK
        uses: actions/upload-artifact@v4
        with:
          name: LIFE-plus-APK
          path: /tmp/life_template/build/app/outputs/flutter-apk/app-release.apk
